return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
      preset = "modern",    
      icons = {    
        -- no icons    
        mappings = false,    
        keys = {    
          Up = "↑ ",    
          Down = "↓ ",    
          Left = "← ",    
          Right = "→ ",    
          C = "^ ",    
          M = "⎇ ",    
          D = "⌘ ",    
          S = "󰘶 ",    
          CR = "⏎ ",    
          Esc = "⎋ ",    
          ScrollWheelDown = "⤓ ",    
          ScrollWheelUp = "⤒ ",    
          NL = "␤ ",    
          BS = "⌫ ",    
          Space = "␣ ",                                                                                                                                                              
          Tab = "⇥ ",                                                                                                                                                                
          F1 = "F1",                                                                                                                                                                 
          F2 = "F2",                                                                                                                                                                 
          F3 = "F3",                                                                                                                                                                 
          F4 = "F4",                                                                                                                                                                 
          F5 = "F5",                                                                                                                                                                 
          F6 = "F6",                                                                                                                                                                 
          F7 = "F7",                                                                                                                                                                 
          F8 = "F8",                                                                                                                                                                 
          F9 = "F9",                                                                                                                                                                 
          F10 = "F10",                                                                                                                                                               
          F11 = "F11",                                                                                                                                                               
          F12 = "F12",                                                                                                                                                               
        },                                                                                                                                                                           
      }
  },
  keys = {
    { "<leader>c", "<cmd>bdelete!<cr>", desc="Close Buffer" },
    { "<leader>s", group = "Search" },
    { "<leader>sb", "<cmd>Telescope buffers<cr>", desc="Buffers" },
    { "<leader>sc", "<cmd>Telescope commands<cr>", desc="Commands" },
    { "<leader>sf", "<cmd>Telescope find_files<cr>", desc="Find Files" },
    { "<leader>sg", "<cmd>Telescope live_grep<cr>", desc="Live Grep" },
    { "<leader>sG", function() require('telescope.builtin').grep_string({search = vim.fn.input('Rg> ')}) end, desc="grep" },
    { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc="Keymaps" },
    { "<leader>sl", "<cmd>Telescope resume<cr>", desc="Resume Last Search" },
    { "<leader>sr", "<cmd>Telescope oldfiles<cr>", desc="Open Recent File" },
    { "<leader>sR", "<cmd>Telescope registers<cr>", desc="Registers" },
    { "<leader>e", function() vim.diagnostic.open_float() end, desc = "Show Error", ft = "beancount" },
    { "<leader>t", group = "Toggle" },
    { "<leader>tg", function() require('gitsigns').toggle_signs() end, desc="Git Signs" },
    { "<leader>th", "<cmd>set hlsearch!<cr>", desc="Highligh Search" },
    { "<leader>tn", "<cmd>set number!<cr>", desc="Line Number" },
    { "<leader>tw", "<cmd>set wrap!<cr>", desc="Wrap" },
    { "<leader>tz", "<cmd>set spell!<cr>", desc="Spellcheck" },
  },
}
