-- user.plugins first
require "user.plugins"
require "user.options"
require "user.colorscheme"
require "user.whichkey"
require "user.telescope"
require "user.autocommands"
-- require "user.treesitter"
-- require "user.lsp"
-- require "user.rainbow-delimiters"
-- require "user.neogit"
--require "user.cmp"
--require "user.dap"
--require "user.gitsigns"
--require "user.comment"
--require "user.indentblankline"
--require "user.symbols-outline"

