require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.telescope"
require "user.whichkey"
require "user.colorscheme"
require "user.gitsigns"
require "user.nvim-tree"